# Generated by Django 4.1.1 on 2022-09-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Başlık")),
                ("content", models.TextField(max_length=350, verbose_name="Açıklama")),
                ("comment_count", models.IntegerField(verbose_name="Yorum sayısı")),
                ("view_count", models.IntegerField(verbose_name="Görüntülenme")),
                ("like_count", models.IntegerField(verbose_name="Beğeni sayısı")),
                (
                    "publish_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Yayınlanma tarihi"
                    ),
                ),
            ],
        ),
    ]
