# Generated by Django 4.1 on 2022-09-12 06:22

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_profile_delete_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="post_images")),
                ("caption", models.TextField()),
                ("created_at", models.DateTimeField(default=datetime.datetime)),
                ("no_of_likes", models.IntegerField(default=0)),
            ],
        ),
    ]
